services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: >
      uvicorn src.api.main:build_api
              --factory
              --reload
              --host 0.0.0.0
              --port 8000
    volumes:
      - ./src:/app/src/:ro
      - ./config_dist:/app/config_dist:ro
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BUBER_DINNER_CONFIG_PATH=config_dist/config.prod.toml

  db:
    container_name: db
    image: postgres:16
    restart: on-failure
    ports:
      - 15432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 20s
      retries: 5
    env_file:
      - ./.env

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    volumes:
      - ./config_dist:/app/config_dist:ro
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head
    environment:
      - DB_HOST=db
      - BUBER_DINNER_CONFIG_PATH=config_dist/config.prod.toml
