services:
  # DinD: https://github.com/testcontainers/testcontainers-python/pull/368
  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    command: pytest tests -s -vv
