services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: >
      uvicorn src.api.main:build_api
              --factory
              --reload
              --host 0.0.0.0
              --port 8000
    volumes:
      - ./config_dist:/app/config_dist:ro
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: clickhouse/clickhouse-server:24.3.2-alpine
    volumes:
      - ./db_data:/var/lib/clickhouse/
    ports:
      - 8123:8123
      - 9000:9000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 2s
      timeout: 2s
      retries: 16
    env_file:
      - ./.env

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    command: alembic
