services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: >
      uvicorn src.api.main:build_api
              --factory
              --reload
              --host 0.0.0.0
              --port 8000
    volumes:
      - ./src:/app/src/:ro
      - ./config_dist:/app/config_dist:ro
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: cockroachdb/cockroach:v23.1.18-fips
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node
    volumes:
      - ./db_data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5
    env_file:
      - ./.env

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    volumes:
      - ./config_dist:/app/config_dist:ro
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head
    environment:
      - DB_HOST=db
