@host=http://localhost:8000

POST {{host}}/auth/register
Content-Type: application/json

{
    "first_name": "",
    "last_name": "",
    "email": "amichai@mantinband.com",
    "password": "Amiko1232!"
}
