[jwt]
jwt_secret = "super-secret-key"
expiry_minutes = 0

[db]
sa_db = "clickhouse"
sa_engine = "asynch"
host = "localhost"
port = 9000
database = "buber_dinner"
user = "buber_dinner"
password = "buber_dinner"
