"""init

Revision ID: eb0f0c187061
Revises:
Create Date: 2024-04-11 20:53:19.394817

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "eb0f0c187061"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
