"""add dinner and review ids

Revision ID: ce36bb5a6f47
Revises: da2515e67606
Create Date: 2024-04-19 22:44:03.190949

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce36bb5a6f47"
down_revision: Union[str, None] = "da2515e67606"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_dinner_ids",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("menu_id", sa.Uuid(), nullable=False),
        sa.Column("dinner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["dinner_id"], ["dinner.id"]),
        sa.ForeignKeyConstraint(["menu_id"], ["menu.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_review_ids",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("menu_id", sa.Uuid(), nullable=False),
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["menu_id"], ["menu.id"]),
        sa.ForeignKeyConstraint(["review_id"], ["menu_review.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menu_review_ids")
    op.drop_table("menu_dinner_ids")
    # ### end Alembic commands ###
