"""init

Revision ID: 684db1bbd454
Revises:
Create Date: 2024-04-13 17:18:26.439017

"""

from typing import Sequence, Union

import clickhouse_sqlalchemy
import clickhouse_sqlalchemy.engines
import sqlalchemy as sa
from alembic import op

import src.infrastructure.persistence.db.types
from src.application.menu.dto.average_rating import AverageRatingDTO

# revision identifiers, used by Alembic.
revision: str = "684db1bbd454"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu",
        sa.Column("id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False),
        sa.Column("name", clickhouse_sqlalchemy.types.common.String(length=100), nullable=False),
        sa.Column(
            "description",
            clickhouse_sqlalchemy.types.common.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "average_rating",
            src.infrastructure.persistence.db.types.dataclass.DataclassType(AverageRatingDTO),
            nullable=False,
        ),
        sa.Column("host_id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False),
        sa.Column(
            "created_date_time",
            clickhouse_sqlalchemy.types.common.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_date_time",
            clickhouse_sqlalchemy.types.common.DateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        clickhouse_sqlalchemy.engines.Memory(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menu")
    # ### end Alembic commands ###
