"""add menu items

Revision ID: 59291836f520
Revises: 9c297c215f3f
Create Date: 2024-04-19 07:14:35.024453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59291836f520"
down_revision: Union[str, None] = "9c297c215f3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("menu_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["menu_id"], ["menu_sections.menu_id"]),
        sa.ForeignKeyConstraint(["section_id"], ["menu_sections.id"]),
        sa.PrimaryKeyConstraint("id", "section_id", "menu_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menu_items")
    # ### end Alembic commands ###
