"""init

Revision ID: 88a29840f990
Revises:
Create Date: 2024-04-12 18:18:45.019575

"""

from typing import Sequence, Union

import clickhouse_sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88a29840f990"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu",
        sa.Column("id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False),
        sa.Column("name", clickhouse_sqlalchemy.types.common.String(), nullable=False),
        sa.Column("description", clickhouse_sqlalchemy.types.common.String(), nullable=False),
        sa.Column("average_rating", clickhouse_sqlalchemy.types.common.Decimal(), nullable=False),
        sa.Column("host_id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False),
        sa.Column(
            "created_date_time", clickhouse_sqlalchemy.types.common.DateTime(), nullable=False,
        ),
        sa.Column(
            "updated_date_time", clickhouse_sqlalchemy.types.common.DateTime(), nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menu")
    # ### end Alembic commands ###
