name: CI

on:
  workflow_call:

  pull_request:
    branches: ["dev"]
  push:
    branches: ["dev"]

env:
  PYTHON_VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: yezz123/setup-uv@v4
      - name: Install dependencies
        run: uv pip install --python $(which python${{ env.PYTHON_VERSION }}) -r requirements/dev.txt

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Lint with pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: yezz123/setup-uv@v4
      - name: Install tests dependencies
        run: uv pip install --python $(which python${{ env.PYTHON_VERSION }}) -r requirements/test.txt
      - name: Run tests
        run: pytest tests/ -s -vv
